/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IO_Dziekanat;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Add_Edit_Ratings extends javax.swing.JPanel {

    String ID_stud;

    /**
     * Creates new form Add_Edit_Change
     */
    public Add_Edit_Ratings() {
        initComponents();
        Panel();
    }

    public void Panel() {
        add_ratings.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        TF1.setVisible(false);
        TF2.setVisible(false);
        Save.setVisible(false);
        Mysql sql = new Mysql();
        
        try {
            String baza[][] = new String[3][sql.Count_students()];
            baza = sql.List_students();
            list_students.addItem("[wybierz]");
            for (int i = 0; i < sql.Count_students(); i++) {
                list_students.addItem(baza[i][0] + " " + baza[i][2] + " " + baza[i][1]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_Edit_Ratings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        list_students = new javax.swing.JComboBox();
        list_student_ratings = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        add_ratings = new javax.swing.JButton();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        list_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_studentsActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        list_student_ratings.setViewportView(jList1);

        add_ratings.setText("Wstaw");
        add_ratings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ratingsActionPerformed(evt);
            }
        });

        L1.setText("Przedmiot:");

        L2.setText("Ocena:");

        Save.setText("Zapisz");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list_student_ratings, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(list_students, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_ratings))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L1)
                                    .addComponent(L2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(TF2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Save)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list_students, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_ratings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_student_ratings, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_studentsActionPerformed
        System.out.println(list_students.getSelectedItem());
        String name = list_students.getSelectedItem().toString();
        if (name == "[wybierz]") {
        } else {
            add_ratings.setVisible(true);
            Short_ID S_ID = new Short_ID();
            String ID = S_ID.ID_K(name);
            ID_stud = ID;

            Mysql sql = new Mysql();
            try {
                String baza[][] = new String[3][sql.Count_student(ID)];
                baza = sql.View_students(ID);
                String[] klient = new String[sql.Count_student(ID)];
                for (int i = 0; i < sql.Count_student(ID); i++) {
                    klient[i] = baza[i][1] + " " + baza[i][1] + " " + baza[i][2];
                }
                jList1.setListData(klient);
            } catch (SQLException ex) {
                Logger.getLogger(Add_Edit_Ratings.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_list_studentsActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String index = (String) jList1.getSelectedValue();
        System.out.println(index);
    }//GEN-LAST:event_jList1MouseClicked

    private void add_ratingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ratingsActionPerformed
        L1.setVisible(true);
        L2.setVisible(true);
        TF1.setVisible(true);
        TF2.setVisible(true);
        Save.setVisible(true);
    }//GEN-LAST:event_add_ratingsActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String subject = TF1.getText();
        String ratings = TF2.getText();
        if (!TF1.getText().equals("") && !TF2.getText().equals("")) {
            System.out.print("OK");
        } else {
            System.out.print("Fail");
        }
    }//GEN-LAST:event_SaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JButton Save;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JButton add_ratings;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane list_student_ratings;
    private javax.swing.JComboBox list_students;
    // End of variables declaration//GEN-END:variables
}
